# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7239d783dc7582325984383d3bfcf18f52d5aa4533301cc4957562c7da8084f05e3b3a64401a29767f78cb9d90f2891610232aa6d533f0d3b612da52bd3cd8cc

test:
  secret_key_base: 44423971cbe6b94939d2d0b7a0764ec66fa1788d9880700d600f77e8145aec53027583cacf5811e42c1fb31679380e60ebf760361304318f61077d6fd9f49a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
